Neos:
  MetaData:
    defaultDimensionSpacePoint:
      language: en
    dimensions:
      'language':
        values:
          'en':
            label: English
          'de':
            label: Deutsch

    metaDataProperties:
      'copyright':
        type: string
        globalScope: true
        ui:
          label: 'Neos.MetaData:Main:properties.copyright'
          inspector:
            editor: 'Neos.Neos/Inspector/Editors/TextAreaEditor'
            editorOptions:
              rows: 7
              required: true
      'altText':
        type: string
        ui:
          label: 'Neos.MetaData:Main:properties.altText'
      'ai':
        type: boolean
        ui:
          label: 'Neos.MetaData:Main:properties.altText'
      'textarea':
        type: string
        ui:
          label: 'Neos.MetaData:Main:properties.altText'
          editor: 'Neos.Neos/Inspector/Editors/TextAreaEditor'
      'caption':
        type: string
        ui:
          label: 'Neos.MetaData:Main:properties.caption'
          inspector:
            editor: 'Neos.Neos/Inspector/Editors/TextAreaEditor'
            editorOptions:
              rows: 7
  Neos:
    userInterface:
      translation:
        autoInclude:
          Neos.MetaData:
            - 'Main'
  Fusion:
    defaultContext:
      AssetMetaData: 'Neos\MetaData\Helper\AssetMetaDataHelper'
